export default Types ={
  FETCH_LIST_MOVIES_REQUEST:'FETCH_LIST_MOVIES_REQUEST',
  FETCH_LIST_MOVIES_SUCCESS:'FETCH_LIST_MOVIES_SUCCESS',
  FETCH_LIST_MOVIES_FAILURE:'FETCH_LIST_MOVIES_FAILURE',
  REFRESH_LIST_MOVIES:'REFRESH_LIST_MOVIES',
  SEARCH_MOVIE_WITH_NAME_SUCCESS:'SEARCH_MOVIE_WITH_NAME_SUCCESS',
} 