export default Types ={
  /* MOVIE TYPES  */

  FETCH_LIST_MOVIES_REQUEST:'FETCH_LIST_MOVIES_REQUEST',
  FETCH_LIST_MOVIES_SUCCESS:'FETCH_LIST_MOVIES_SUCCESS',
  FETCH_LIST_MOVIES_FAILURE:'FETCH_LIST_MOVIES_FAILURE',
  REFRESH_LIST_MOVIES:'REFRESH_LIST_MOVIES',
  SEARCH_MOVIE_WITH_NAME_SUCCESS:'SEARCH_MOVIE_WITH_NAME_SUCCESS',

  /* PLAN TYPES */
  ADD_MOVIE_PLAN_SUCCESS:'ADD_MOVIE_PLAN_SUCCESS',

  /* AUTHENTICATION FIREBASE */
  LOGIN_REQUEST:'LOGIN_REQUEST',
  LOGIN_SUCCESS :'LOGIN_SUCCESS',
  LOGIN_ERROR:'LOGIN_ERROR',
  LOGOUT_SUCCESS:'LOGOUT_SUCCESS'
} 